services:
  - type: web
    name: uh-lms-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://uh-lms-frontend.onrender.com
      - key: DHL_API_URL
        value: https://xmlpi-ea.dhl.com/XMLShippingServlet
      - key: DHL_SITE_ID
        sync: false
      - key: DHL_PASSWORD
        sync: false
      - key: DHL_UNIFIED_API_KEY
        sync: false
      - key: DHL_UNIFIED_API_SECRET
        sync: false
      - key: UPS_CLIENT_ID
        sync: false
      - key: UPS_CLIENT_SECRET
        sync: false
      - key: UPS_ACCOUNT
        sync: false
      - key: METABASE_URL
        value: https://metabase.ultrahuman.com
      - key: METABASE_SESSION
        sync: false
      - key: METABASE_QUESTION_ID
        value: "19100"

  - type: web
    name: uh-lms-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://uh-lms-backend.onrender.com
